version: '2'
services:
    blogpostsrepo-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BlogPostsRepo/mongodb/:/data/db/
